const DB = window.TIRECARE_DB;
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const out = $('#result');
const input = $('#query');
const compact = v => String(v || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
const valveKey = v => compact(v).replace(/^TV/, '').replace(/^TR/, '');
const safe = v => String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uniq = a => [...new Set((a || []).filter(Boolean))];
let memoryInventory = [];
function loadInventory(){ try { return JSON.parse(localStorage.getItem('tirecare_inventory') || '[]'); } catch { return memoryInventory; } }
function saveInventory(rows){ memoryInventory = rows; try { localStorage.setItem('tirecare_inventory', JSON.stringify(rows)); } catch {} }
function card(title, body, badge='AIRLOCK'){ out.innerHTML = `<article class="panel"><div class="panel-badge">${safe(badge)}</div><h2>${safe(title)}</h2>${body}</article>`; out.scrollIntoView({behavior:'smooth',block:'start'}); }
function list(items){ return `<ol class="steps">${(items || []).map(x => `<li>${safe(x)}</li>`).join('')}</ol>`; }
function sourceBlock(src){ if(!src) return ''; const items = Array.isArray(src) ? src : [src]; return `<div class="source-list"><b>Sources</b>${items.map(s => typeof s === 'string' ? `<span>${safe(s)}</span>` : `<span>${safe(s.name || 'Source')}${s.url ? ` — <a href="${safe(s.url)}" target="_blank" rel="noreferrer">open</a>` : ''}</span>`).join('')}</div>`; }
function allValveKeys(v){ return uniq([v.code, v.tr, v.haltec, v.part, ...(v.aliases || [])]).map(valveKey); }
function familyCandidates(f){ return uniq([f.canonical, ...(f.aliases || []), ...(f.sizes || []), ...(f.fitments || []).flatMap(x => [x[0], x[1]])]); }
function valveMatches(q){ const k = valveKey(q); if(!k) return []; const exact = DB.valves.filter(v => allValveKeys(v).includes(k)); if(exact.length) return exact; if(k.length >= 3) return DB.valves.filter(v => allValveKeys(v).some(x => x.startsWith(k) || k.startsWith(x))); return []; }
function fitMatches(q){ const k = compact(q); if(!k) return []; const exact = DB.fitmentFamilies.filter(f => familyCandidates(f).some(x => compact(x) === k)); if(exact.length) return exact; if(k.length >= 4) return DB.fitmentFamilies.filter(f => familyCandidates(f).some(x => { const z = compact(x); return z.includes(k) || k.includes(z); })); return []; }
function knowledgeMatches(q){ const k = compact(q); if(!k) return []; return (DB.knowledgeIndex || []).filter(x => [x.title, x.summary, ...(x.keywords || [])].some(v => { const z = compact(v); return z === k || (k.length > 3 && (z.includes(k) || k.includes(z))); })); }
function renderValve(v){ card(v.code, `<div class="detail-grid"><div><b>Type</b><span>${safe(v.class || 'Valve')}</span></div><div><b>Pressure</b><span>${safe(v.pressure || 'VERIFY EXACT MANUFACTURER')}</span></div><div><b>Rim hole</b><span>${safe(v.hole || 'Application-specific')}</span></div><div><b>Effective length</b><span>${safe(v.length || 'Varies')}</span></div><div><b>Use</b><span>${safe(v.use || 'Application-specific')}</span></div><div><b>Aliases</b><span>${safe(uniq([v.tr,v.haltec,v.part,...(v.aliases || [])]).join(', ') || v.code)}</span></div></div>${v.note ? `<p class="warning">${safe(v.note)}</p>` : ''}${v.replace ? `<p><b>Service / replace:</b> ${safe(v.replace)}</p>` : ''}${v.hydro ? '<p class="ok">Air/liquid service capable where specified.</p>' : ''}${sourceBlock(v.sources)}`, 'VALVE LOGIC'); }
function renderValveList(items,q){ card(`Valve matches for “${q}”`, `<p class="lead">Multiple records match. Choose the exact valve instead of guessing.</p><div class="fit-grid">${items.map(v => `<button class="result-choice" data-valve="${safe(v.code)}"><strong>${safe(v.code)}</strong><span>${safe(v.class || 'Valve')}</span><span>${safe(v.hole || '')}</span><span>${safe(v.pressure || '')}</span></button>`).join('')}</div>`, 'MULTIPLE MATCHES'); $$('[data-valve]').forEach(b => b.onclick = () => renderValve(DB.valves.find(v => v.code === b.dataset.valve))); }
function renderFit(f){ card(f.canonical, `<p class="lead">${safe(f.application)} • ${safe(f.construction || 'Application-specific')}</p><p class="warning">${safe(f.warning || 'Verify exact wheel/valve configuration before final selection.')}</p><div class="fit-grid">${(f.fitments || []).map(x => `<div class="fit"><strong>${safe(x[1])}</strong><span>Article ${safe(x[0])}</span><span>Offset: ${safe(x[2] || 'Verify')}</span><span>${safe(x[3] || '')}</span></div>`).join('')}</div>${f.sizes?.length ? `<h3>Covered/searchable sizes</h3><div class="chips">${f.sizes.map(x => `<span>${safe(x)}</span>`).join('')}</div>` : ''}${sourceBlock(f.sources)}`, 'VERIFIED FITMENT'); }
function renderFitList(items,q){ card(`Fitment matches for “${q}”`, `<p class="lead">This input maps to multiple verified families. Choose the actual application/wheel setup.</p><div class="fit-grid">${items.map((f,i) => `<button class="result-choice" data-fit="${i}"><strong>${safe(f.canonical)}</strong><span>${safe(f.application)}</span><span>${safe(f.warning || '')}</span></button>`).join('')}</div>`, 'MULTIPLE FITMENTS'); $$('[data-fit]').forEach(b => b.onclick = () => renderFit(items[Number(b.dataset.fit)])); }
function renderKnowledgeHit(hit){ card(hit.title, `<p class="lead">${safe(hit.summary)}</p>${hit.details ? list(hit.details) : ''}${sourceBlock(hit.sources)}`, 'VERIFIED KNOWLEDGE'); }
function search(){ const q = input.value.trim(); if(!q) return; const valves = valveMatches(q); if(valves.length === 1) return renderValve(valves[0]); if(valves.length > 1) return renderValveList(valves,q); const fits = fitMatches(q); if(fits.length === 1) return renderFit(fits[0]); if(fits.length > 1) return renderFitList(fits,q); const hits = knowledgeMatches(q); if(hits.length) return renderKnowledgeHit(hits[0]); const k = q.toLowerCase(); if(/pressure|psi|placard/.test(k)) return modulePressure(); if(/patch|puncture|repair|leak/.test(k)) return modulePatch(); if(/tpms|relearn|sensor/.test(k)) return moduleValves(); card('UNKNOWN — no verified local match', `<p>Search: <b>${safe(q)}</b></p><p class="warning">The local database does not contain a verified record for this exact input. TireCare will not make one up.</p><div class="button-row"><button id="browseUnknown">Browse Knowledge Base</button><button id="runTestsUnknown">Run Coverage Test</button></div>`, 'AIRLOCK STOP'); $('#browseUnknown').onclick = moduleKnowledge; $('#runTestsUnknown').onclick = moduleSelfTest; }
function moduleDashboard(){ card('System Status', `<div class="stat-grid"><div><b>${DB.fitmentFamilies.length}</b><span>fitment families loaded</span></div><div><b>${DB.valves.length}</b><span>valve records loaded</span></div><div><b>${(DB.knowledgeIndex||[]).length}</b><span>knowledge topics</span></div></div><h3>Verified now</h3>${list(DB.audit?.verifiedNow || [])}<h3>Not claimed complete</h3>${list(DB.audit?.notYetClaimedComplete || [])}<p class="warning">${safe(DB.audit?.rule || 'Unknown critical data stays UNKNOWN.')}</p><div class="button-row"><button id="statusTest">Run Coverage Test</button><button id="statusBrowse">Browse Database</button></div>`, 'DATA STATUS'); $('#statusTest').onclick = moduleSelfTest; $('#statusBrowse').onclick = moduleKnowledge; }
function moduleKnowledge(){ card('Knowledge Base', `<div class="stat-grid"><div><b>${DB.fitmentFamilies.length}</b><span>fitment families</span></div><div><b>${DB.valves.length}</b><span>valve records</span></div><div><b>${(DB.knowledgeIndex||[]).length}</b><span>knowledge topics</span></div></div><div class="tool-row"><input id="kbFilter" placeholder="413, 600HP, 16.9R38, TR440, article number..."><button id="kbFilterBtn">FILTER</button></div><h3>Valve records</h3><div class="browse-grid">${DB.valves.map(v => `<button class="browse-item" data-kb-valve="${safe(v.code)}"><b>${safe(v.code)}</b><span>${safe(v.class || v.use || 'Valve')}</span></button>`).join('')}</div><h3>Fitment families</h3><div class="browse-grid">${DB.fitmentFamilies.map((f,i) => `<button class="browse-item" data-kb-fit="${i}"><b>${safe(f.canonical)}</b><span>${safe(f.application)}</span></button>`).join('')}</div>`, 'LIVE DATABASE'); $$('[data-kb-valve]').forEach(b => b.onclick = () => renderValve(DB.valves.find(v => v.code === b.dataset.kbValve))); $$('[data-kb-fit]').forEach(b => b.onclick = () => renderFit(DB.fitmentFamilies[Number(b.dataset.kbFit)])); const go = () => { const q=$('#kbFilter').value.trim(); if(!q)return; input.value=q; search(); }; $('#kbFilterBtn').onclick=go; $('#kbFilter').onkeydown=e=>e.key==='Enter'&&go(); }
function moduleFitment(){ card('Tire / Tube Logic', `<p class="lead">Search a tire size, tube article number, or valve. All verified matches are shown when more than one configuration exists.</p><div class="tool-row"><input id="fitInput" placeholder="16.9R38, 70075016, 552-070, 6.50R10"><button id="fitGo">LOOK UP</button></div><div class="button-row"><button id="browseFit">Browse all data</button><button id="testFit">Run coverage test</button></div><h3>AIRLOCK rules</h3>${list(DB.airlock)}`, 'FITMENT ENGINE'); const go=()=>{input.value=$('#fitInput').value;search();}; $('#fitGo').onclick=go; $('#fitInput').onkeydown=e=>e.key==='Enter'&&go(); $('#browseFit').onclick=moduleKnowledge; $('#testFit').onclick=moduleSelfTest; }
function moduleCalculator(){const M=window.TIRE_MATH;card('Tire Size Math',`<p class="lead">Decode one metric or flotation size, or compare two sizes. Results are dimensional math—not fitment, load, wheel-width, or pressure approval.</p><div class="calculator-grid"><label>Original size<input id="sizeA" placeholder="205/55R17"></label><label>Comparison size<input id="sizeB" placeholder="225/50R17"></label><label>Indicated speed (MPH)<input id="speedAt" type="number" min="1" value="60"></label><button id="calculateSizes">CALCULATE</button></div><div id="sizeMathResult"></div><h3>Calculated size-space datasets</h3><p>The generator covers <b>${M.countSpace('passenger').toLocaleString()}</b> passenger-shaped and <b>${M.countSpace('lt').toLocaleString()}</b> LT-shaped combinations. Every exported row is labeled <b>CALCULATED_NOT_MARKET_VERIFIED</b>.</p><div class="button-row"><button data-export="passenger">DOWNLOAD PASSENGER CSV</button><button data-export="lt">DOWNLOAD LT CSV</button></div><p class="warning">${safe(M.disclaimer)}</p>`,'DIMENSIONAL REFERENCE');const fmt=g=>`<div class="stat-grid"><div><b>${safe(g.raw)}</b><span>Parsed size</span></div><div><b>${g.overallDiameterIn} in</b><span>Overall diameter</span></div><div><b>${g.sectionWidthIn} in</b><span>Nominal section width</span></div><div><b>${g.sidewallIn} in</b><span>Sidewall height</span></div><div><b>${g.circumferenceIn} in</b><span>Circumference</span></div><div><b>${g.revolutionsPerMile}</b><span>Revolutions per mile</span></div></div>`;$('#calculateSizes').onclick=()=>{const a=$('#sizeA').value.trim(),b=$('#sizeB').value.trim(),speed=Number($('#speedAt').value)||60,ga=M.geometry(a);if(!ga)return $('#sizeMathResult').innerHTML='<p class="warning">Original size was not recognized. Try 205/55R17 or 33X12.50R15.</p>';if(!b)return $('#sizeMathResult').innerHTML=fmt(ga);const c=M.compare(a,b,speed);if(!c)return $('#sizeMathResult').innerHTML='<p class="warning">Comparison size was not recognized.</p>';$('#sizeMathResult').innerHTML=fmt(c.first)+fmt(c.second)+`<div class="${c.withinThreePercent?'ok':'warning'}"><b>${Math.abs(c.diameterDifferencePercent)}% diameter difference</b><br>At ${c.speedometerMph} MPH indicated: approximately ${c.actualMph} MPH by rolling-diameter math.<br>${c.withinThreePercent?'Within the common ±3% comparison screen; still not fitment approval.':'Outside the common ±3% screen; escalate clearance, load, wheel, gearing and vehicle-system checks.'}</div>`;};$$('[data-export]').forEach(b=>b.onclick=()=>{const kind=b.dataset.export,blob=new Blob([M.toCsv(M.generateSizeSpace(kind))],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`tirecare-${kind}-calculated-size-space.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
function modulePressure(){ card('PressureLogic', `<p class="lead">${safe(DB.pressure.placardRule)}</p><div class="pressure-box"><label>Front placard cold PSI<input id="frontPsi" inputmode="numeric" placeholder="35"></label><label>Rear placard cold PSI<input id="rearPsi" inputmode="numeric" placeholder="35"></label><label>Measured front PSI<input id="frontNow" inputmode="numeric" placeholder="32"></label><label>Measured rear PSI<input id="rearNow" inputmode="numeric" placeholder="34"></label></div><button id="pressureCompare">COMPARE TO PLACARD</button><div id="pressureResult"></div><h3>Placard workflow</h3>${list(DB.pressure.compare)}<p class="warning">${safe(DB.pressure.hardStop)}</p>${sourceBlock(DB.pressure.sources)}`, 'PLACARD FIRST'); $('#pressureCompare').onclick=()=>{const vals=['frontPsi','rearPsi','frontNow','rearNow'].map(id=>Number($('#'+id).value));if(vals.some(n=>!Number.isFinite(n)||n<=0))return $('#pressureResult').innerHTML='<p class="warning">Enter all four positive PSI values. This compares readings; it does not invent placard data.</p>';const [fp,rp,fn,rn]=vals,df=fn-fp,dr=rn-rp;$('#pressureResult').innerHTML=`<div class="stat-grid"><div><b>${df===0?'ON TARGET':Math.abs(df)+' PSI '+(df<0?'LOW':'HIGH')}</b><span>Front vs placard</span></div><div><b>${dr===0?'ON TARGET':Math.abs(dr)+' PSI '+(dr<0?'LOW':'HIGH')}</b><span>Rear vs placard</span></div></div>`;}; }
function moduleValves(){ card('ValveLogic + TPMS', `<p class="lead">Enter the number exactly how it appears in the shop. TR/TV prefixes and common aliases are normalized.</p><div class="tool-row"><input id="valveInput" placeholder="413, 600HP, 501, 618A, TV-413"><button id="valveGo">FIND VALVE</button></div><h3>Valve records</h3><div class="browse-grid">${DB.valves.map(v => `<button class="browse-item" data-vquick="${safe(v.code)}"><b>${safe(v.code)}</b><span>${safe(v.pressure || v.use || '')}</span></button>`).join('')}</div><h3>TPMS AIRLOCK rules</h3>${list(DB.tpms.rules)}<h3>Verified relearn examples</h3>${DB.tpms.examples.map(e=>`<div class="mini"><b>${safe(e.vehicle)}</b><span>${safe(e.type)} • ${safe(e.method)}</span><span>Drive: ${safe(e.drive)}</span></div>`).join('')}<h3>Leak diagnosis</h3>${list(DB.tpms.diagnosis)}${sourceBlock(DB.tpms.sources)}`, 'VALVE / SENSOR'); const go=()=>{input.value=$('#valveInput').value;search();}; $('#valveGo').onclick=go; $('#valveInput').onkeydown=e=>e.key==='Enter'&&go(); $$('[data-vquick]').forEach(b=>b.onclick=()=>renderValve(DB.valves.find(v=>v.code===b.dataset.vquick))); }
function modulePatch(){ card('Patch Notes', `<div class="motto">${safe(DB.patchNotes.motto)}</div><div class="button-row"><button data-patch="puncture">Puncture</button><button data-patch="tube">Tube</button><button data-patch="stop">No-go / escalate</button></div><div id="patchFlow"></div>${sourceBlock(DB.patchNotes.sources)}`, 'REPAIR WORKFLOW'); const show=type=>{const title=type==='puncture'?'Puncture workflow':type==='tube'?'Tube repair':'Stop and escalate';$('#patchFlow').innerHTML=`<h3>${title}</h3>${list(DB.patchNotes[type])}`;}; $$('[data-patch]').forEach(b=>b.onclick=()=>show(b.dataset.patch)); show('puncture'); }
function moduleTraining(){ card('TrainingLogic', `<p class="lead">${safe(DB.training.philosophy)}</p><div class="button-row"><button data-train="quick">QUICK</button><button data-train="learn">LEARN</button><button data-train="why">WHY?</button></div><div id="trainingMode"></div><h3>Progression</h3>${list(DB.training.levels)}<h3>Training rules</h3>${list(DB.training.rules)}`, 'TRAINING'); const show=m=>$('#trainingMode').innerHTML=`<p class="ok"><b>${m.toUpperCase()}:</b> ${safe(DB.training.modes[m])}</p>`; $$('[data-train]').forEach(b=>b.onclick=()=>show(b.dataset.train)); show('learn'); }
function moduleInventory(){ card('InventoryLogic', `<p class="lead">Working local inventory notebook. Entries save in this browser until the real shop inventory is imported.</p><div class="inventory-form"><input id="invPart" placeholder="Part # / valve"><input id="invDesc" placeholder="Description"><input id="invQty" type="number" min="0" placeholder="Qty"><input id="invBin" placeholder="Bin / location"><button id="invAdd">ADD</button></div><div id="invTable"></div>`, 'LOCAL INVENTORY'); const draw=()=>{const rows=loadInventory();$('#invTable').innerHTML=rows.length?`<div class="inventory-table">${rows.map((r,i)=>`<div class="inventory-row"><b>${safe(r.part)}</b><span>${safe(r.desc)}</span><span>Qty ${safe(r.qty)}</span><span>${safe(r.bin)}</span><button data-del="${i}">×</button></div>`).join('')}</div>`:'<p class="warning">No local inventory entries yet.</p>';$$('[data-del]').forEach(b=>b.onclick=()=>{const rows=loadInventory();rows.splice(Number(b.dataset.del),1);saveInventory(rows);draw();});}; $('#invAdd').onclick=()=>{const part=$('#invPart').value.trim(),desc=$('#invDesc').value.trim(),qty=$('#invQty').value.trim(),bin=$('#invBin').value.trim();if(!part)return;const rows=loadInventory();rows.push({part,desc,qty:qty||'?',bin});saveInventory(rows);$('#invPart').value=$('#invDesc').value=$('#invQty').value=$('#invBin').value='';draw();}; draw(); }
function moduleSelfTest(){ const cases=[['413','valve'],['TR413','valve'],['600HP','valve'],['501','valve'],['218A','valve'],['440','valve'],['618A','valve'],['9.00R20','fit'],['6.50R10','fit'],['15R19.5','fit'],['11R22.5','fit'],['20X8.00-10','fit'],['16.9R38','fit'],['552-070','fit']]; const rows=cases.map(([q,t])=>({q,t,ok:(t==='valve'?valveMatches(q):fitMatches(q)).length>0})); const pass=rows.filter(x=>x.ok).length; card('Built-in Coverage Test', `<div class="stat-grid"><div><b>${pass}/${rows.length}</b><span>core tests passed</span></div><div><b>${DB.valves.length}</b><span>valves loaded</span></div><div><b>${DB.fitmentFamilies.length}</b><span>fitment families loaded</span></div></div><div class="test-list">${rows.map(r=>`<div class="test-row ${r.ok?'test-pass':'test-fail'}"><b>${safe(r.q)}</b><span>${r.ok?'PASS':'FAIL'}</span></div>`).join('')}</div>${pass===rows.length?'<p class="ok">All built-in core searches resolve against the loaded database.</p>':'<p class="warning">One or more core searches failed. Do not demo this build until they pass.</p>'}`, 'SELF TEST'); }
const modules={fitment:moduleFitment,calculator:moduleCalculator,pressure:modulePressure,valves:moduleValves,patch:modulePatch,training:moduleTraining,inventory:moduleInventory,knowledge:moduleKnowledge,status:moduleDashboard,selftest:moduleSelfTest};
$('#searchBtn').addEventListener('click',search); input.addEventListener('keydown',e=>e.key==='Enter'&&search()); $$('[data-q]').forEach(b=>b.onclick=()=>{input.value=b.dataset.q;search();}); $$('[data-module]').forEach(b=>b.onclick=()=>modules[b.dataset.module]?.());
function initThree(){if(!window.THREE)return;try{const host=$('#three-bg'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100),renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);host.appendChild(renderer.domElement);const tire=new THREE.Mesh(new THREE.TorusGeometry(2.5,.95,22,80),new THREE.MeshBasicMaterial({color:0x4dd7b5,wireframe:true,transparent:true,opacity:.1}));tire.rotation.x=.65;tire.rotation.z=.35;scene.add(tire);camera.position.z=7;(function tick(){tire.rotation.y+=.0025;tire.rotation.z+=.0008;renderer.render(scene,camera);requestAnimationFrame(tick);})();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});}catch(e){console.warn('Three.js disabled',e);}}
initThree();
moduleDashboard();
