const DB=window.TIRECARE_DB;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const out=$('#result');
const input=$('#query');
const compact=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const valveKey=v=>compact(v).replace(/^TV/,'').replace(/^TR/,'');
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function card(title,body,badge='AIRLOCK'){out.innerHTML=`<article class="panel"><div class="panel-badge">${badge}</div><h2>${title}</h2>${body}</article>`;out.scrollIntoView({behavior:'smooth',block:'start'});}
function allValveKeys(v){return [v.code,v.tr,v.haltec,v.part,...(v.aliases||[])].filter(Boolean).map(valveKey);}
function findValve(q){const k=valveKey(q);return DB.valves.find(v=>allValveKeys(v).includes(k));}
function familyCandidates(f){return [f.canonical,...(f.aliases||[]),...(f.sizes||[]),...(f.fitments||[]).flatMap(x=>[x[0],x[1]])].filter(Boolean);}
function findFit(q){const k=compact(q);let exact=DB.fitmentFamilies.find(f=>familyCandidates(f).some(x=>compact(x)===k));if(exact)return exact;return DB.fitmentFamilies.find(f=>(f.sizes||[]).some(x=>compact(x)===k));}
function findArticle(q){const k=compact(q);return DB.fitmentFamilies.find(f=>(f.fitments||[]).some(x=>compact(x[0])===k));}
function sourceBlock(src){if(!src)return '';const list=Array.isArray(src)?src:[src];return `<div class="source-list"><b>Verified source</b>${list.map(s=>`<span>${safe(s.name||s)}${s.url?` — <a href="${safe(s.url)}" target="_blank" rel="noreferrer">source</a>`:''}</span>`).join('')}</div>`;}
function renderValve(v){card(v.code,`<div class="detail-grid"><div><b>Type</b><span>${safe(v.class||'Valve')}</span></div><div><b>Pressure</b><span>${safe(v.pressure||'Verify exact manufacturer')}</span></div><div><b>Rim hole</b><span>${safe(v.hole||'Application-specific')}</span></div><div><b>Effective length</b><span>${safe(v.length||'Varies')}</span></div><div><b>Best for</b><span>${safe(v.use||'See application')}</span></div><div><b>TR / cross refs</b><span>${safe([v.tr,...(v.aliases||[])].filter(Boolean).join(', ')||v.code)}</span></div></div>${v.note?`<p class="warning">${safe(v.note)}</p>`:''}${v.replace?`<p><b>Change/service when:</b> ${safe(v.replace)}</p>`:''}${v.hydro?'<p class="ok">Air/liquid service capable where specified.</p>':''}${sourceBlock(v.sources)}`,'VERIFIED VALVE');}
function renderFit(f){card(f.canonical,`<p class="lead">${safe(f.application)} • ${safe(f.construction||'Application-specific')}</p><p class="warning">${safe(f.warning||'Verify exact wheel/valve configuration before final selection.')}</p><div class="fit-grid">${(f.fitments||[]).map(x=>`<div class="fit"><strong>${safe(x[1])}</strong><span>Article ${safe(x[0])}</span><span>Offset: ${safe(x[2]||'Verify')}</span><span>${safe(x[3]||'')}</span></div>`).join('')}</div>${f.sizes?.length?`<h3>Searchable sizes in this family</h3><div class="chips">${f.sizes.map(x=>`<span>${safe(x)}</span>`).join('')}</div>`:''}${sourceBlock(f.sources)}`,'VERIFIED FITMENT');}
function renderKnowledgeHit(hit){card(hit.title,`<p class="lead">${safe(hit.summary)}</p>${hit.details?list(hit.details):''}${sourceBlock(hit.sources)}`,'VERIFIED KNOWLEDGE');}
function searchKnowledge(q){const k=compact(q);return (DB.knowledgeIndex||[]).find(x=>[x.title,x.summary,...(x.keywords||[])].some(v=>compact(v).includes(k)||k.includes(compact(v))));}
function search(){const q=input.value.trim();if(!q)return;const v=findValve(q);if(v)return renderValve(v);const a=findArticle(q);if(a)return renderFit(a);const f=findFit(q);if(f)return renderFit(f);const h=searchKnowledge(q);if(h)return renderKnowledgeHit(h);const k=q.toLowerCase();if(k.includes('pressure')||k.includes('psi')||k.includes('placard'))return modulePressure();if(k.includes('patch')||k.includes('puncture')||k.includes('repair'))return modulePatch();if(k.includes('tpms')||k.includes('relearn')||k.includes('sensor'))return moduleValves();card('No verified direct match',`<p>Search: <b>${safe(q)}</b></p><p class="warning">UNKNOWN — DO NOT GUESS. This exact item is not yet in the verified local database. The app will not fabricate a result.</p><p>Current verified local coverage: <b>${DB.fitmentFamilies.length}</b> fitment families, <b>${DB.valves.length}</b> valve records, plus TPMS, pressure, repair and training rules.</p>`,'UNKNOWN');}
function list(items){return `<ol class="steps">${items.map(x=>`<li>${safe(x)}</li>`).join('')}</ol>`}
function modulePressure(){card('PressureLogic',`<p class="lead">${safe(DB.pressure.placardRule)}</p><h3>Placard workflow</h3>${list(DB.pressure.compare)}<p class="warning">${safe(DB.pressure.hardStop)}</p>${sourceBlock(DB.pressure.sources)}`,'PLACARD FIRST');}
function moduleValves(){card('ValveLogic + TPMS',`<h3>Common service valves</h3><div class="fit-grid">${DB.valves.filter(v=>['TR413','TR600HP','TR501','TR415','TR418','TR602HP','TR801HP'].includes(v.code)).map(v=>`<div class="fit"><strong>${v.code}</strong><span>${safe(v.class)}</span><span>${safe(v.pressure)}</span><span>${safe(v.use)}</span></div>`).join('')}</div><h3>TPMS AIRLOCK rules</h3>${list(DB.tpms.rules)}<h3>Verified relearn examples</h3>${DB.tpms.examples.map(e=>`<div class="mini"><b>${safe(e.vehicle)}</b><span>${safe(e.type)} • ${safe(e.method)}</span><span>Drive: ${safe(e.drive)}</span></div>`).join('')}<h3>What is actually leaking?</h3>${list(DB.tpms.diagnosis)}${sourceBlock(DB.tpms.sources)}`,'VALVE / SENSOR');}
function modulePatch(){card('Patch Notes',`<div class="motto">${safe(DB.patchNotes.motto)}</div><h3>Puncture workflow</h3>${list(DB.patchNotes.puncture)}<h3>Tube repair</h3>${list(DB.patchNotes.tube)}<h3>Stop and escalate</h3>${list(DB.patchNotes.stop)}${sourceBlock(DB.patchNotes.sources)}`,'REPAIR');}
function moduleTraining(){card('TrainingLogic',`<p class="lead">${safe(DB.training.philosophy)}</p><div class="mode-grid"><div><b>QUICK</b><span>${safe(DB.training.modes.quick)}</span></div><div><b>LEARN</b><span>${safe(DB.training.modes.learn)}</span></div><div><b>WHY?</b><span>${safe(DB.training.modes.why)}</span></div></div><h3>Progression</h3>${list(DB.training.levels)}<h3>Training rules</h3>${list(DB.training.rules)}`,'NEW-HIRE MODE');}
function moduleTire(){card('TireLogic',`<h3>Read the sidewall</h3><p>${safe(DB.tireKnowledge.sidewall)}</p><p>${safe(DB.tireKnowledge.commercial)}</p><p>${safe(DB.tireKnowledge.ag)}</p><h3>Rules</h3>${list(DB.tireKnowledge.rules)}<h3>AIRLOCK</h3>${list(DB.airlock)}${sourceBlock(DB.tireKnowledge.sources)}`,'TIRE KNOWLEDGE');}
function moduleInventory(){card('InventoryLogic',`<p>${safe(DB.inventory.status)}</p><div class="chips">${DB.inventory.fields.map(x=>`<span>${safe(x)}</span>`).join('')}</div>`,'SHOP INVENTORY');}
const modules={fitment:moduleTire,pressure:modulePressure,valves:moduleValves,patch:modulePatch,training:moduleTraining,inventory:moduleInventory};
$('#searchBtn').addEventListener('click',search);input.addEventListener('keydown',e=>e.key==='Enter'&&search());$$('[data-q]').forEach(b=>b.onclick=()=>{input.value=b.dataset.q;search();});$$('[data-module]').forEach(b=>b.onclick=()=>modules[b.dataset.module]());
function initThree(){if(!window.THREE)return;const host=$('#three-bg'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100),renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);host.appendChild(renderer.domElement);const geo=new THREE.TorusGeometry(2.5,.95,22,80),mat=new THREE.MeshBasicMaterial({color:0x4dd7b5,wireframe:true,transparent:true,opacity:.12}),tire=new THREE.Mesh(geo,mat);tire.rotation.x=.65;tire.rotation.z=.35;scene.add(tire);camera.position.z=7;function tick(){tire.rotation.y+=.0025;tire.rotation.z+=.0008;renderer.render(scene,camera);requestAnimationFrame(tick)}tick();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});}
initThree();
input.value='413';search();