(function (root) {
  'use strict';
  const MM_PER_INCH=25.4;
  const range=(a,b,s)=>{const out=[];for(let n=a;n<=b;n+=s)out.push(n);return out;};
  const parameters={PASSENGER_WIDTHS:range(125,355,10),PASSENGER_ASPECTS:[20,25,30,35,40,45,50,55,60,65,70,75,80,85],PASSENGER_RIMS:[10,12,13,14,15,16,17,18,19,20,21,22,23,24],LT_WIDTHS:range(155,455,10),LT_ASPECTS:[35,40,45,50,55,60,65,70,75,80,85],LT_RIMS:[14,15,16,16.5,17,17.5,18,19.5,20,22.5,24,24.5]};
  const round=(n,p=2)=>{const k=10**p;return Math.round((n+Number.EPSILON)*k)/k;};
  const normalize=v=>String(v||'').toUpperCase().trim().replace(/\s+/g,'').replace(/,/g,'.');
  function parseMetric(value){const raw=normalize(value),m=raw.match(/^(P|LT|ST|T)?(\d{3})\/(\d{2,3})(ZR|R|D|B|-)(\d{2}(?:\.5)?)(?:\s*(\d{2,3})(?:\/(\d{2,3}))?([A-Z])?)?$/);if(!m)return null;const[,prefix='',width,aspect,construction,rim,loadIndex='',dualLoadIndex='',speedSymbol='']=m;return{raw,prefix,widthMm:Number(width),aspectRatio:Number(aspect),construction:construction==='-'?'BIAS':construction,rimIn:Number(rim),loadIndex:loadIndex?Number(loadIndex):null,dualLoadIndex:dualLoadIndex?Number(dualLoadIndex):null,speedSymbol:speedSymbol||null,format:'metric'};}
  function parseFlotation(value){const raw=normalize(value),m=raw.match(/^(LT|ST)?(\d{2,3}(?:\.\d{1,2})?)X(\d{1,2}(?:\.\d{1,2})?)(R|-)(\d{1,2}(?:\.5)?)(?:LT)?$/);if(!m)return null;const[,prefix='',diameter,width,construction,rim]=m;return{raw,prefix,overallDiameterIn:Number(diameter),widthIn:Number(width),construction:construction==='R'?'R':'BIAS',rimIn:Number(rim),format:'flotation'};}
  const parse=v=>parseMetric(v)||parseFlotation(v);
  function geometry(input){const s=typeof input==='string'?parse(input):input;if(!s)return null;if(s.format==='flotation'){const side=(s.overallDiameterIn-s.rimIn)/2;return{...s,sidewallIn:round(side),sidewallMm:round(side*MM_PER_INCH,1),overallDiameterIn:round(s.overallDiameterIn),overallDiameterMm:round(s.overallDiameterIn*MM_PER_INCH,1),sectionWidthIn:round(s.widthIn),circumferenceIn:round(Math.PI*s.overallDiameterIn),revolutionsPerMile:round(63360/(Math.PI*s.overallDiameterIn),1)};}const side=s.widthMm*s.aspectRatio/100,diameter=s.rimIn*MM_PER_INCH+2*side;return{...s,sidewallMm:round(side,1),sidewallIn:round(side/MM_PER_INCH),overallDiameterMm:round(diameter,1),overallDiameterIn:round(diameter/MM_PER_INCH),sectionWidthIn:round(s.widthMm/MM_PER_INCH),circumferenceIn:round(Math.PI*diameter/MM_PER_INCH),revolutionsPerMile:round(63360/(Math.PI*diameter/MM_PER_INCH),1)};}
  function compare(a,b,speedMph=60){const first=geometry(a),second=geometry(b);if(!first||!second)return null;const pct=(second.overallDiameterIn-first.overallDiameterIn)/first.overallDiameterIn*100;return{first,second,diameterDifferenceIn:round(second.overallDiameterIn-first.overallDiameterIn),diameterDifferencePercent:round(pct),speedometerMph:Number(speedMph),actualMph:round(Number(speedMph)*second.overallDiameterIn/first.overallDiameterIn,1),revsPerMileDifference:round(second.revolutionsPerMile-first.revolutionsPerMile,1),withinThreePercent:Math.abs(pct)<=3};}
  function spec(kind){return kind==='lt'?{widths:parameters.LT_WIDTHS,aspects:parameters.LT_ASPECTS,rims:parameters.LT_RIMS}:{widths:parameters.PASSENGER_WIDTHS,aspects:parameters.PASSENGER_ASPECTS,rims:parameters.PASSENGER_RIMS};}
  const countSpace=kind=>{const s=spec(kind);return s.widths.length*s.aspects.length*s.rims.length;};
  function generateSizeSpace(kind='passenger'){const s=spec(kind),lt=kind==='lt',out=[];for(const width of s.widths)for(const aspect of s.aspects)for(const rim of s.rims){const code=`${lt?'LT':''}${width}/${aspect}R${rim}`,g=geometry(code);out.push({code,category:lt?'Light Truck parameter space':'Passenger parameter space',width_mm:width,aspect_ratio:aspect,construction:'R',rim_diameter_in:rim,overall_diameter_in:g.overallDiameterIn,circumference_in:g.circumferenceIn,revolutions_per_mile:g.revolutionsPerMile,status:'CALCULATED_NOT_MARKET_VERIFIED'});}return out;}
  function toCsv(rows){if(!rows.length)return'';const keys=Object.keys(rows[0]),cell=v=>`"${String(v??'').replace(/"/g,'""')}"`;return[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\n');}
  root.TIRE_MATH={MM_PER_INCH,parse,geometry,compare,generateSizeSpace,countSpace,toCsv,parameters,disclaimer:'Calculated size geometry is mathematical reference data, not proof that a size is manufactured, approved for a vehicle, compatible with a wheel, or safe at a particular load or pressure.'};
})(typeof window!=='undefined'?window:globalThis);
