import assert from 'node:assert/strict';
import '../tire-math.js';
const M=globalThis.TIRE_MATH;
const stock=M.geometry('205/55R17');
assert.equal(stock.widthMm,205);
assert.equal(stock.sidewallMm,112.8);
assert.equal(stock.overallDiameterIn,25.88);
assert.equal(M.geometry('33X12.50R15').overallDiameterIn,33);
assert.equal(M.parse('LT285/70R17').prefix,'LT');
assert.equal(M.parse('315/70R22.5 154/150L').dualLoadIndex,150);
assert.equal(M.geometry('not-a-size'),null);
const comparison=M.compare('205/55R17','225/50R17',60);
assert.ok(comparison);
assert.ok(Number.isFinite(comparison.actualMph));
assert.equal(M.countSpace('passenger'),4704);
assert.equal(M.countSpace('lt'),4092);
const rows=M.generateSizeSpace('passenger');
assert.equal(rows.length,4704);
assert.ok(rows.every(r=>r.status==='CALCULATED_NOT_MARKET_VERIFIED'));
assert.match(M.toCsv(rows.slice(0,2)),/CALCULATED_NOT_MARKET_VERIFIED/);
console.log('tire-math: all tests passed');
