(function(root){
'use strict';
const C=root.TIRE_CATALOG;if(!C)return;
const clean=v=>String(v??'').trim().toUpperCase().replace(/[–—]/g,'-');
const compact=v=>clean(v).replace(/[^A-Z0-9.]/g,'');
const tireKey=v=>compact(v).replace(/^P(?=\d)/,'').replace(/ZR/g,'R');
const uniqueObjects=arr=>{const seen=new Set();return(arr||[]).filter(x=>{const k=JSON.stringify(x);if(seen.has(k))return false;seen.add(k);return true;});};
const round=(n,d=2)=>Number(Number(n).toFixed(d));
const extract=input=>C.extractCandidate?C.extractCandidate(input):null;
function normalize(input){const found=extract(input);if(found)return clean(found).replace(/\s+/g,'');let s=clean(input).replace(/\s+/g,'');if(/^\d{3}\d{2}R\d{2}(?:\.5)?$/.test(s))s=s.replace(/^(\d{3})(\d{2})(R\d{2}(?:\.5)?)$/,'$1/$2$3');if(/^(P|LT|ST)?\d{3}\d{2}\d{2}$/.test(s)){const m=s.match(/^(P|LT|ST)?(\d{3})(\d{2})(\d{2})$/);s=`${m[1]||''}${m[2]}/${m[3]}R${m[4]}`;}return s;}
function parse(input){const raw=clean(input),s=normalize(input);let m=s.match(/^(P|LT|ST)?(\d{3})\/(\d{2,3})(ZR|R|-)(\d{2}(?:\.5)?)$/);if(m){const width=+m[2],aspect=+m[3],rim=+m[5],side=width*aspect/100;let family='passenger_metric';if(m[1]==='LT')family='light_truck_metric';else if(m[1]==='ST')family='special_trailer_metric';else if(rim%1)family='commercial_metric';else if(width>=365||rim>=28)family='ag_metric';return{raw,normalized:`${m[1]||''}${width}/${aspect}${m[4]}${rim}`,family,prefix:m[1]||'',widthMm:width,aspectRatio:aspect,construction:m[4],rimIn:rim,sidewallMm:round(side),overallDiameterIn:round((rim*25.4+2*side)/25.4),circumferenceIn:round(Math.PI*(rim*25.4+2*side)/25.4)};}
m=s.match(/^(VF|IF)(\d{3})\/(\d{2,3})R(\d{2}(?:\.5)?)$/);if(m){const width=+m[2],aspect=+m[3],rim=+m[4],side=width*aspect/100;return{raw,normalized:`${m[1]}${width}/${aspect}R${rim}`,family:'ag_metric',prefix:m[1],widthMm:width,aspectRatio:aspect,construction:'R',rimIn:rim,sidewallMm:round(side),overallDiameterIn:round((rim*25.4+2*side)/25.4)};}
m=s.match(/^(\d{2,3}(?:\.\d{1,2})?)X(\d{1,2}(?:\.\d{1,2})?)(R|-)(\d{1,2}(?:\.5)?)$/);if(m)return{raw,normalized:s,family:(+m[1]<=36&&+m[4]<=16)?'atv_lawn_flotation':'flotation',overallDiameterIn:+m[1],sectionWidthIn:+m[2],construction:m[3],rimIn:+m[4]};
m=s.match(/^(\d{2,3}(?:\.\d{1,2})?)X(\d{1,2}(?:\.\d{1,2})?)-(\d{1,2}(?:\.5)?)$/);if(m)return{raw,normalized:s,family:(+m[1]<=36&&+m[3]<=16)?'atv_lawn_flotation':'flotation',overallDiameterIn:+m[1],sectionWidthIn:+m[2],construction:'-',rimIn:+m[3]};
m=s.match(/^(\d{1,2}(?:\.\d{1,2})?)(LR|L|R|-)(\d{1,2}(?:\.5)?)$/);if(m)return{raw,normalized:s,family:(m[2]==='L'||m[2]==='LR')?'implement_ag':'numeric_or_ag',sectionWidthIn:+m[1],construction:m[2],rimIn:+m[3]};
m=s.match(/^(\d{3})\/(\d{2,3})(R|D|-)(\d{2}(?:\.5)?)$/);if(m)return{raw,normalized:s,family:(+m[4]%1)?'commercial_metric':'ag_or_industrial_metric',widthMm:+m[1],aspectRatio:+m[2],construction:m[3],rimIn:+m[4]};return null;}
function baseTubeMatches(q){const k=compact(q);if(!k)return[];return(C.TUBES||[]).filter(t=>compact(`${t.article} ${t.size} ${t.valve} ${t.application}`).includes(k)||compact(t.article)===k);}
function airlocMatches(q){const candidate=extract(q)||normalize(q),k=compact(q);return(C.AIRLOC_FITMENTS||[]).filter(f=>compact(f.stock)===k||compact(f.tube)===k||(f.fits||[]).some(x=>tireKey(x)===tireKey(candidate)));}
function valveMatches(q){const k=compact(q).replace(/^TV/,'TR');const all=[...(C.VALVES||[]),...(C.EXTRA_VALVES||[])];return uniqueObjects(all.filter(v=>[v.code,...(v.aliases||[])].some(x=>compact(x).replace(/^TV/,'TR')===k)));}
function tpmsMatches(q){const k=compact(q);if(!k)return[];return(C.TPMS_PRODUCTS||[]).filter(p=>compact(p.part)===k||compact(`${p.maker} ${p.name} ${p.frequency} ${(p.service||[]).join(' ')}`).includes(k));}
function browniesMatches(q){const cand=extract(q)||normalize(q),k=compact(q);return(C.BROWNIES_MODELS||[]).filter(m=>compact(`${m.brand} ${m.model}`).includes(k)||(parse(q)&&(m.sizes||[]).some(s=>tireKey(s)===tireKey(cand))));}
function flapMatches(q){const cand=extract(q)||normalize(q),k=compact(q);return(C.FLAPS||[]).filter(f=>compact(f.stock)===k||(f.fits||[]).some(x=>tireKey(x)===tireKey(cand)));}
function pressureGuidance(parsed){if(!parsed)return null;if(parsed.family==='passenger_metric')return'Operating PSI: use the vehicle tire-information placard or owner information for the specified COLD pressure. Tire size and valve maximum pressure are not the vehicle target PSI.';return'Operating PSI cannot be safely determined from tire size alone. Verify the exact tire/equipment, actual load, axle/application, speed/service and the applicable manufacturer load-inflation information or vehicle/equipment specification.';}
function compatibility(input){const parsed=parse(input),manufacturer=baseTubeMatches(input),airloc=airlocMatches(input),tubeMatches=uniqueObjects([...manufacturer,...airloc]);return{input,parsed,tubeMatches,manufacturerMatches:manufacturer,airlocMatches:airloc,status:tubeMatches.length?C.STATUS.VERIFIED_PRODUCT:(parsed?C.STATUS.GENERATED_NOMENCLATURE:C.STATUS.UNKNOWN),warning:tubeMatches.length?'Source-backed tube records exist. Multiple records can be valid for different applications, wheel valve positions, tube construction or supplier families. Verify the actual wheel and application before installation.':parsed?'Recognized tire designation. No verified tube fitment in the loaded source set matches it; do not infer a tube from diameter alone.':'Input is not recognized as a tire designation.',pressureGuidance:pressureGuidance(parsed)};}
function search(q){const tire=parse(q),tubes=uniqueObjects([...baseTubeMatches(q),...airlocMatches(q)]),valves=valveMatches(q),tpms=tpmsMatches(q),brownies=browniesMatches(q),flaps=flapMatches(q),compatibilityResult=tire?compatibility(q):null;const verified=tubes.length||valves.length||tpms.length||brownies.length||flaps.length;return{query:q,tire,tubes,valves,tpms,brownies,flaps,compatibility:compatibilityResult,status:verified?C.STATUS.VERIFIED_PRODUCT:(tire?C.STATUS.GENERATED_NOMENCLATURE:C.STATUS.UNKNOWN)};}
const oldAudit=C.audit.bind(C);function audit(){const b=oldAudit();return{...b,version:'1.2.0-runtime-safe',airlocFitmentRecords:(C.AIRLOC_FITMENTS||[]).length,airlocFitAliases:(C.AIRLOC_FITMENTS||[]).reduce((n,x)=>n+(x.fits||[]).length,0),tpmsProducts:(C.TPMS_PRODUCTS||[]).length,browniesObservedModels:(C.BROWNIES_MODELS||[]).length,browniesObservedSizeListings:(C.BROWNIES_MODELS||[]).reduce((n,x)=>n+(x.sizes||[]).length,0),flapRecords:(C.FLAPS||[]).length,extraValveRecords:(C.EXTRA_VALVES||[]).length,sourceCount:Object.keys(C.SOURCES||{}).length};}
C.normalizeTireSize=normalize;C.parseTireSize=parse;C.search=search;C.compatibilityForTire=compatibility;C.searchValves=valveMatches;C.audit=audit;C.pressureGuidance=pressureGuidance;C.RUNTIME_SAFE=true;
root.TIRE_CATALOG=C;
})(typeof window!=='undefined'?window:globalThis);
