(function(){
'use strict';
const C=window.TIRE_CATALOG;if(!C)return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const result=$('#result'),input=$('#query');
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uniqueSources=items=>{const seen=new Set();return(items||[]).filter(Boolean).filter(s=>{const u=s.url||s.name||String(s);if(seen.has(u))return false;seen.add(u);return true;});};
function sourceBlock(items){const ss=uniqueSources(items);if(!ss.length)return'';return`<div class="source-list"><b>References</b>${ss.map(s=>typeof s==='string'?`<span>${safe(s)}</span>`:`<span><a href="${safe(s.url||'#')}" target="_blank" rel="noreferrer">${safe(s.name||'Source')}</a>${s.scope?` — ${safe(s.scope)}`:''}</span>`).join('')}</div>`;}
function panel(title,body,badge='DEEP CATALOG'){result.innerHTML=`<article class="panel"><div class="panel-badge">${safe(badge)}</div><h2>${safe(title)}</h2>${body}</article>`;result.scrollIntoView({behavior:'smooth',block:'start'});}
function designation(t){if(!t)return'';return`<h3>Recognized tire designation</h3><div class="detail-grid"><div><b>Normalized</b><span>${safe(t.normalized)}</span></div><div><b>Family</b><span>${safe(String(t.family||'').replaceAll('_',' '))}</span></div>${t.widthMm?`<div><b>Width</b><span>${safe(t.widthMm)} mm</span></div>`:''}${t.aspectRatio?`<div><b>Aspect ratio</b><span>${safe(t.aspectRatio)}</span></div>`:''}${t.sectionWidthIn?`<div><b>Section width</b><span>${safe(t.sectionWidthIn)} in</span></div>`:''}${t.rimIn?`<div><b>Rim</b><span>${safe(t.rimIn)} in</span></div>`:''}${t.construction?`<div><b>Construction</b><span>${safe(t.construction)}</span></div>`:''}${t.overallDiameterIn?`<div><b>Calculated OD</b><span>${safe(t.overallDiameterIn)} in</span></div>`:''}</div>`;}
function tubeCard(t){if(t.stock)return`<div class="fit"><strong>${safe(t.tube)}</strong><span>Air-Loc stock ${safe(t.stock)}</span><span>Valve ${safe(t.valve)}</span><span>${safe(t.category)}</span><span>Source-backed ALSO FITS relationship</span></div>`;return`<div class="fit"><strong>${safe(t.size||'Tube')}</strong><span>Firestone article ${safe(t.article||'—')}</span><span>Valve ${safe(t.valve||'Verify')}</span><span>${safe(t.application||'')} ${t.origin?`• ${safe(t.origin)}`:''}</span>${t.valveOffset?`<span>Valve position: ${safe(t.valveOffset)}</span>`:''}</div>`;}
function valveCard(v){return`<div class="fit"><strong>${safe(v.code)}</strong><span>${safe(v.type||v.bore||v.application||'Valve reference')}</span>${v.rimHoleIn?`<span>Rim hole: ${safe(v.rimHoleIn)} in</span>`:''}<span>${v.maxPsi?`Published max: ${safe(v.maxPsi)} PSI`:'Pressure: verify exact product/application'}</span>${v.application?`<span>${safe(v.application)}</span>`:''}${v.notes?`<span>${safe(v.notes)}</span>`:''}</div>`;}
function tpmsCard(p){return`<div class="fit"><strong>${safe(p.maker)} ${safe(p.part)}</strong><span>${safe(p.name)}</span><span>Frequency: ${safe(p.frequency)}</span><span>Stem: ${safe(p.stem||'Verify product')}</span><span>${safe(p.programming||'Verify programming/application')}</span>${p.service?.length?`<span>Service parts: ${safe(p.service.join(', '))}</span>`:''}${p.nutTorque?`<span>Nut torque: ${safe(p.nutTorque)}</span>`:''}${p.screwTorque?`<span>Screw torque: ${safe(p.screwTorque)}</span>`:''}</div>`;}
function browniesCard(m){return`<div class="fit"><strong>${safe(m.brand)} ${safe(m.model)}</strong><span>Brownie's public catalog observation</span><span>${safe(m.sizes.length)} listed sizes captured</span>${m.url?`<span><a href="${safe(m.url)}" target="_blank" rel="noreferrer">Open Brownie's listing</a></span>`:''}</div>`;}
function flapCard(f){return`<div class="fit"><strong>${safe(f.stock)} • ${safe(f.dimension)}</strong><span>${safe(f.position)}</span><span>${safe(f.category)}</span></div>`;}
function renderSearch(q){const r=C.search(q),has=!!(r.tire||r.tubes?.length||r.valves?.length||r.tpms?.length||r.brownies?.length||r.flaps?.length);if(!has)return false;const refs=[];let body='';if(r.tire){body+=designation(r.tire);const c=r.compatibility;body+=`<p class="${c?.tubeMatches?.length?'ok':'warning'}"><b>${c?.tubeMatches?.length?'SOURCE-BACKED FITMENT FOUND':'RECOGNIZED SIZE — FITMENT NOT YET VERIFIED'}</b><br>${safe(c?.warning||'Recognized tire designation.')}</p>`;if(c?.pressureGuidance)body+=`<p class="warning"><b>PressureLogic:</b> ${safe(c.pressureGuidance)}</p>`;}
if(r.tubes?.length){body+=`<h3>Tube options / cross-references</h3><p class="lead">These are source-backed records, not automatic substitutions. If more than one appears, wheel/application/valve position decides which one is right.</p><div class="fit-grid">${r.tubes.map(t=>{refs.push(t.source);return tubeCard(t);}).join('')}</div>`;}
if(r.valves?.length){body+=`<h3>Valve references</h3><div class="fit-grid">${r.valves.map(v=>{refs.push(v.source);return valveCard(v);}).join('')}</div><p class="warning">Valve maximum pressure is a component rating. It is not the tire/vehicle operating PSI.</p>`;}
if(r.tpms?.length){body+=`<h3>TPMS products</h3><div class="fit-grid">${r.tpms.map(p=>{refs.push(p.source);return tpmsCard(p);}).join('')}</div><p class="warning"><b>TPMS AIRLOCK:</b> tire size does not select the sensor. Confirm year, make, model/platform, direct vs indirect system, protocol/frequency and then program/relearn as required.</p>`;}
if(r.brownies?.length){body+=`<h3>Brownie's catalog matches</h3><div class="fit-grid">${r.brownies.map(m=>{refs.push(m.source);return browniesCard(m);}).join('')}</div><p class="warning">Brownie's website listing is a public retail-catalog observation. It does not prove physical on-hand quantity at the Glenwood store.</p>`;}
if(r.flaps?.length){body+=`<h3>Flap references</h3><div class="fit-grid">${r.flaps.map(f=>{refs.push(f.source);return flapCard(f);}).join('')}</div>`;}
body+=sourceBlock(refs);panel(`Catalog result: ${q}`,body,r.status);return true;}
function renderCatalog(){const a=C.audit();panel('Deep Research Catalog',`<p class="lead">A tire designation is parsed first. Product fitment is a separate layer and only appears when a loaded source supports it.</p><div class="stat-grid"><div><b>${(a.generatedTotal||0).toLocaleString()}</b><span>generated metric nomenclature combinations</span></div><div><b>${a.verifiedTubeProducts||0}</b><span>Firestone manufacturer tube records</span></div><div><b>${a.airlocFitmentRecords||0}</b><span>Air-Loc cross-reference records</span></div><div><b>${a.airlocFitAliases||0}</b><span>Air-Loc searchable fit aliases</span></div><div><b>${a.verifiedValveReferences||0}</b><span>base valve references</span></div><div><b>${a.extraValveRecords||0}</b><span>extra shop valve records</span></div><div><b>${a.tpmsProducts||0}</b><span>TPMS product records</span></div><div><b>${a.browniesObservedSizeListings||0}</b><span>captured Brownie's model-size listings</span></div><div><b>${a.flapRecords||0}</b><span>flap records</span></div></div><h3>Try the real regression cases</h3><div class="quick-chips">${['type M, 255/65, 15','255/65R15','P255/65R15','16.9R38','420/85R38','31x10.50R15','11R22.5','20x7-8','TR413','600HP','TR501','TR618A','33500','5001','HTS-A78DH','300020','255/65R18'].map(q=>`<button data-deep-q="${safe(q)}">${safe(q)}</button>`).join('')}</div><h3>Coverage rules</h3><ol class="steps"><li>Recognized notation is not treated as an unknown tire just because a local product row is missing.</li><li>Air-Loc ALSO FITS entries are tube-coverage relationships, not claims that the tire sizes themselves are equivalent.</li><li>Firestone manufacturer records remain distinct from distributor cross-references.</li><li>TPMS selection requires vehicle-specific data; tire size alone never selects a sensor.</li><li>Operating pressure is placard/load-table logic, never copied from a valve maximum rating.</li><li>Brownie's public catalog is not the same as physical shop inventory.</li></ol>${sourceBlock([C.SOURCES.FIRESTONE_HOME,C.SOURCES.AIRLOC_2022,C.SOURCES.BROWNIES,C.SOURCES.SCHRADER,C.SOURCES.DILL_TPMS,C.SOURCES.HAMATON,C.SOURCES.AUTEL_TPMS,C.SOURCES.HALTEC_HP])}`,'CATALOG STATUS');$$('[data-deep-q]').forEach(b=>b.onclick=()=>{input.value=b.dataset.deepQ;renderSearch(b.dataset.deepQ);});}
function runRegression(){const tests=[['type M, 255/65, 15',r=>r.tire?.normalized==='255/65R15'&&r.tubes?.length>=2],['255/65R15',r=>r.tubes?.some(x=>x.stock==='TU02377')&&r.tubes?.some(x=>x.stock==='TU02246')],['P255/65R15',r=>r.tubes?.length>=2],['16.9R38',r=>r.tire&&r.tubes?.length>0],['420/85R38',r=>r.tire&&r.tubes?.length>0],['31x10.50R15',r=>r.tire&&r.tubes?.length>0],['11R22.5',r=>r.tire&&r.tubes?.length>0],['20x7-8',r=>r.tire&&r.tubes?.length>0],['TR413',r=>r.valves?.length>0],['600HP',r=>r.valves?.length>0],['TR501',r=>r.valves?.length>0],['TR618A',r=>r.valves?.length>0],['33500',r=>r.tpms?.some(x=>x.part==='33500')],['5001',r=>r.tpms?.some(x=>x.part==='5001')],['HTS-A78DH',r=>r.tpms?.some(x=>x.part==='HTS-A78DH')],['300020',r=>r.tpms?.some(x=>x.part==='300020')],['255/65R18',r=>r.tire&&r.brownies?.length>0],['definitely-not-a-tire-xyz',r=>!r.tire&&!r.tubes?.length&&!r.valves?.length&&!r.tpms?.length]];return tests.map(([q,fn])=>{let r,e;try{r=C.search(q);return{query:q,pass:!!fn(r),result:r};}catch(err){e=String(err);return{query:q,pass:false,error:e};}});}
function showRegression(){const rows=runRegression(),pass=rows.filter(x=>x.pass).length;panel('Deep Catalog Regression Test',`<div class="stat-grid"><div><b>${pass}/${rows.length}</b><span>tests passed</span></div><div><b>${pass===rows.length?'PASS':'FAIL'}</b><span>catalog engine</span></div></div><div class="test-list">${rows.map(x=>`<div class="test-row ${x.pass?'test-pass':'test-fail'}"><b>${safe(x.query)}</b><span>${x.pass?'PASS':'FAIL'}</span></div>`).join('')}</div>`,'REGRESSION');}
const nav=document.querySelector('.nav-inner');if(nav&&!document.querySelector('[data-deep-catalog]')){const b=document.createElement('button');b.dataset.deepCatalog='1';b.textContent='DEEP CATALOG';b.onclick=renderCatalog;nav.appendChild(b);}const grid=document.querySelector('.module-grid');if(grid&&!document.querySelector('.deep-catalog-card')){const b=document.createElement('button');b.className='module-card deep-catalog-card';b.innerHTML='<span class="icon">◎</span><strong>Deep Catalog</strong><small>Firestone + Air-Loc + Brownie\'s + TPMS + valves</small><em>OPEN DEEP CATALOG →</em>';b.onclick=renderCatalog;grid.appendChild(b);}if(grid&&!document.querySelector('.deep-test-card')){const b=document.createElement('button');b.className='module-card deep-test-card';b.innerHTML='<span class="icon">✓</span><strong>Catalog Regression</strong><small>Run messy-size, tube, valve, TPMS and Brownie\'s tests</small><em>RUN TESTS →</em>';b.onclick=showRegression;grid.appendChild(b);}
const searchBtn=$('#searchBtn');if(searchBtn)searchBtn.addEventListener('click',e=>{const q=input.value.trim();if(q&&renderSearch(q)){e.preventDefault();e.stopImmediatePropagation();}},true);if(input)input.addEventListener('keydown',e=>{if(e.key==='Enter'){const q=input.value.trim();if(q&&renderSearch(q)){e.preventDefault();e.stopImmediatePropagation();}}},true);
window.TIRE_CATALOG_UI={renderCatalog,renderSearch,runRegression,showRegression};
})();
